version: "3.3"
services:
  ts-app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '18018:18018'
    container_name: bitmunt-typescript
    image: ts-app
    command: ["npm", "run", "start"]
    volumes:
      - ./data:/app/data
